language: node_js
node_js:
  - "8"
cache:
  directories:
    - $HOME/.npm
install:
  - npm i -g npm@6
  - travis_retry npm ci
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
